### ISSUE TITLE
Throws an error when dealing with nested folders

### ISSUE THREAD

**Issue by JacobDB** [aquafadas-com/gulp-php-minify#1]
This module looks awesome, looking to integrate it in to my WordPress theme development workflow. I'm having an issue where if I include sub-folders in a glob, an error gets thrown:

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: EEXIST: file already exists, mkdir '/Users/me/Repositories/project-name/dist/sub-folder'
    at Error (native)
```

My task is fairly large, so I've just put [my entire gulpfile on pastebin](http://pastebin.com/Rs13N5Ei). The relevant task starts at line 230, the PHP minification happens at line 259, if the flag `--dist` gets passed.

My sourcecode is all in [this repository](https://github.com/revxx14/new-site), though the gulpfile isn't quite up to date with the one in that patsebin.

I'd love some help getting this working properly! Thanks!

**Comment by cedx** [comment]
Sorry for the delay: we were very busy these last months.

The error that you have does not seem to be related to this plugin:
`Error: EEXIST: file already exists, mkdir`

The plugin does not create folders by itself, it let Gulp.js handle this aspect. So your issue may be related to these ones :
https://github.com/gulpjs/gulp/issues/422
https://github.com/gulpjs/gulp/issues/1544

The problem probably lies in the way you provide your sources to Gulp (with `gulp.src`).

I've looked at the content of your provided `gulpfile.js` : I think you should really look closer at the documentation concerning the usage of our plugin.

> The plugin takes a list of PHP scripts as input.

You're using the following sources:
`gulp.src([src + "/**/*", "!" + src + "{/assets,/assets/**,/screenshot.png}"])`

That's problematic : the plugin will receive every kind of files, instead of only PHP scripts. This can lead to errors: the plugin is unable to minify a non-PHP file or a directory.

Currently, the plugin has no way to detect that a file is a PHP script or not (we can't rely on the file extension, and we are not inspecting the file contents because it is useless for the plugin itself, and a bad design for its performance).

> The plugin only needs the file paths, so you should specify the `read` option to `false` when providing the file list, and you should not have any other plugin before it.

So you should really use this kind of sources (and split your `html` task into subtasks):
`gulp.src(src + "/**/*.php", {read: false}).pipe(phpMinify()).pipe(gulp.dest(htmlDirectory))`

I hope it helped you.

**Comment by JacobDB** [comment]
Good information, thank you. When I have a few spare minutes to work on this again, I'll give it a shot and report back.
